export const themes = {
  light: {
    foregroundHeader: '#6a6a6a',
    backgroundHeader: '#f2f2f2',
    backDropHeader: '#ffffffdd',
    foreground: '#000000',
    iconSmall: 'black',
    icon: '#171717',
    foregroundSwitch: '#1a1a1adf',
    backgroundSwitch: '#fafafadf',
    foregroundAddButton: '#ffffff',
    backgroundAddButton: '#000000',
  },
  dark: {
    foregroundHeader: '#f2f2f2',
    backgroundHeader: '#1a1a1a',
    backDropHeader: '#000000dd',
    foreground: '#dadada',
    iconSmall: '#f2f2f2',
    icon: 'white',
    foregroundSwitch: '#fafafadf',
    backgroundSwitch: '#212121df',
    foregroundAddButton: '#000000',
    backgroundAddButton: '#ffffff',
  },
  main: {
    background: '#ffd8fb',
    theme: '#f995f0',
  },
};
